### ISSUE TITLE
kana-p AUR repo?

### ISSUE THREAD

**Issue by Lokke** [bragagia/kana-p#1]
https://aur.archlinux.org/packages/kana-p/
https://aur.archlinux.org/packages/kana-p-dev/

booth down

**Comment by bragagia** [comment]
Yes, i will try to re-up them, but they are currently too few documented to be on the AUR.
I planned to work on that this week-end.

**Comment by bragagia** [comment]
kana-p is again on the AUR on the name kana-p-git.
It will replace the old package on install.

**Comment by Lokke** [comment]
thank you
